### PR TITLE
Update Dockerfile centos7

### PR DESCRIPTION
**Pull request by Maratk1n**
Fixes for #15 .

1. Specify sipsak version
2. Install cjson

### CODE REVIEW

**Comment by miconda** [comment]
Thanks! Can lua cjson package be installed via luarocks? This way should be a more standard approach.

**Comment by Maratk1n** [comment]
@miconda, I've updated PR.

**Comment by miconda** [comment]
Isn't luarocks a package on centos 7? I was trying to avoid installing from tarballs or git when packages are available on the OS repo. I would expect that luarocks is a common need for any distro, being something similar to pip for python.

**Comment by Maratk1n** [comment]
Unfortunately, Centos 7 repository doesn't have this package
```
$ docker run -it centos:7 /bin/bash
[root@d92c48d44746 /]# yum search all luarocks
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.axelname.ru
 * extras: mirror.axelname.ru
 * updates: mirror.docker.ru
base                                                                                                                                                                                | 3.6 kB  00:00:00     
extras                                                                                                                                                                              | 2.9 kB  00:00:00     
updates                                                                                                                                                                             | 2.9 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                                                                                                                       | 153 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                                                                                                                   | 232 kB  00:00:00     
(3/4): base/7/x86_64/primary_db                                                                                                                                                     | 6.1 MB  00:00:00     
(4/4): updates/7/x86_64/primary_db                                                                                                                                                  | 6.5 MB  00:00:01     
Warning: No matches found for: luarocks
No matches found
```
And I could not find a simple way to install.

**Comment by miconda** [comment]
On a quick web check, it seems to be availabe via EPEL repo -- hope was not hitting misinformation:

```
yum -y install epel-release
yum repolist
yum -y install luarocks
```

**Comment by Maratk1n** [comment]
@miconda , thanks! You're right.

**Comment by miconda** [comment]
Thanks!

**Pull request merged**
