### PR TITLE
thacxx0005 - http_async_client suspend on reply

### PR DESCRIPTION
**Pull request by giavac**
This test does something unusual: performs an `http_async_query()` in the reply route for a 200 to INVITE, then suspends again with a new `http_async_query()`.

### CODE REVIEW

**Comment by miconda** [comment]
Thanks! You can merge it!

**Comment by giavac** [comment]
Thanks @miconda - This is actually going to fail without a change in Kamailio that I'm preparing to submit.
I've actually created this test scenario to help anybody willing to review that change (tm module) and get a better idea.
I'll leave it as a branch for now, and will review later depending on the outcome of the review.

**Comment by miconda** [comment]
OK.

**Comment by giavac** [comment]
Added multiple `http_async_client` workers, and a new scenario (thacxx0006) with a SIP request re-suspended to perform a new HTTP query.

thacxx0005 will fail until https://github.com/kamailio/kamailio/pull/2721 is merged
thacxx0006 works already.

**Comment by miconda** [comment]
OK, thanks! Once the PR for Kamailio is merged, this one can be merged as well.

**Comment by giavac** [comment]
Merged with new tests thacxx0005 (which required https://github.com/kamailio/kamailio/pull/2721 - just merged) and thacxx0006.

thacxx0005 is expected to work only with kamailio master for now.

**Pull request merged**
