### PR TITLE
Dockerfile.centos7: fix container building

### PR DESCRIPTION
**Pull request by Maratk1n**
1. Install nmap-ncat
2. Exclude new modules that couldn't be compiled

### CODE REVIEW

**Comment by Maratk1n** [comment]
@miconda , may you take a look, please?

**Comment by miconda** [comment]
Thanks for the reminder! I can merge it.

Do you know if libjwt and libwebsockets are available on centos 7 and if yes, what versions are there?

**Comment by miconda** [comment]
@sergey-safarov: maybe you can help with information about libjwt and libwebsockets on centos 7. You can also do changes to the docker files, kamailio developers should have git commit access to this repo now.

**Comment by Maratk1n** [comment]
Looks like Centos 7 repository doesn't have this packages
```
[root@78247e5a501f /]# yum search all jwt
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.docker.ru
 * extras: mirrors.datahouse.ru
 * updates: mirrors.datahouse.ru
============================================================================================== Matched: jwt ===============================================================================================
python-jwt.noarch : JSON Web Token implementation in Python
[root@78247e5a501f /]# 
[root@78247e5a501f /]# 
[root@78247e5a501f /]# yum search all websockets
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.docker.ru
 * extras: mirrors.datahouse.ru
 * updates: mirrors.datahouse.ru
=========================================================================================== Matched: websockets ===========================================================================================
qt5-qtwebsockets.i686 : Qt5 - WebSockets component
qt5-qtwebsockets.x86_64 : Qt5 - WebSockets component
qt5-qtwebsockets-devel.i686 : Development files for qt5-qtwebsockets
qt5-qtwebsockets-devel.x86_64 : Development files for qt5-qtwebsockets
qt5-qtwebsockets-doc.noarch : API documentation for qt5-qtwebsockets
qt5-qtwebsockets-examples.x86_64 : Programming examples for qt5-qtwebsockets
```
I've checked it in the container
```
$ docker run -it centos:7 /bin/bash
```

**Comment by miconda** [comment]
OK, thanks!

**Pull request merged**
